// Este arquivo já foi atualizado anteriormente e deve estar correto.
// Apenas para garantir que está no CodeProject.
import type { User, Vehicle } from "@/types"

export const mockUser: User = {
  id: "user123",
  nome: "Usuário Teste",
  email: "teste@ocar.com",
  tipo: "comprador",
  photoURL: "/placeholder.svg?width=40&height=40",
  createdAt: new Date(),
  updatedAt: new Date(),
  cidade: "São Paulo",
  cpf: "123.456.789-00",
  telefone: "(11) 99999-9999",
  saldo: 500,
}

export const mockVehicles: Vehicle[] = [
  {
    id: "1",
    donoId: "seller1",
    marca: "Volkswagen",
    modelo: "Gol",
    versao: "1.0 MPI Total Flex 8V 5p",
    ano: 2022,
    cor: "Branco",
    quilometragem: 15000,
    motor: "1.0 MPI",
    combustivel: ["Flex"],
    cambio: "manual",
    opcionais: ["Ar Condicionado", "Direção Hidráulica", "Vidros Elétricos"],
    preco: 65000,
    fipe: 63000,
    placaParcial: "ABC-1D34",
    numeroProprietarios: 1,
    observacoes: "Carro em excelente estado, único dono.",
    fotos: [
      "/placeholder.svg?width=800&height=600",
      "/placeholder.svg?width=800&height=600",
      "/placeholder.svg?width=800&height=600",
    ],
    plano: "destaque",
    verificado: true,
    favoritos: ["user123"], // Usuário mock já favoritou este
    dataCadastro: new Date(Date.now() - 86400000 * 2), // 2 dias atrás
    status: "ativo",
    cidade: "São Paulo",
    views: 1854,
    likes: 123, // Usuário mock NÃO curtiu este inicialmente
    shares: 45,
  },
  {
    id: "2",
    donoId: "seller2",
    marca: "Fiat",
    modelo: "Strada",
    versao: "Freedom 1.3 Flex 8V CD",
    ano: 2023,
    cor: "Vermelho",
    quilometragem: 5000,
    motor: "1.3 Firefly",
    combustivel: ["Flex"],
    cambio: "manual",
    opcionais: ["Multimídia", "Câmera de Ré", "Rodas de Liga Leve"],
    preco: 92000,
    placaParcial: "XYZ-9G87",
    numeroProprietarios: 1,
    fotos: ["/placeholder.svg?width=800&height=600", "/placeholder.svg?width=800&height=600"],
    plano: "gratuito",
    verificado: false,
    favoritos: [],
    dataCadastro: new Date(Date.now() - 86400000 * 5), // 5 dias atrás
    status: "ativo",
    cidade: "Rio de Janeiro",
    views: 987,
    likes: 88,
    shares: 21,
  },
  {
    id: "3",
    donoId: "seller3",
    marca: "Chevrolet",
    modelo: "Onix",
    versao: "LTZ 1.0 Turbo Flex Aut.",
    ano: 2021,
    cor: "Prata",
    quilometragem: 32000,
    motor: "1.0 Turbo",
    combustivel: ["Flex"],
    cambio: "automatico",
    opcionais: ["Teto Solar", "Park Assist", "Wi-Fi Nativo"],
    preco: 78000,
    fipe: 77000,
    placaParcial: "QWE-5R67",
    numeroProprietarios: 2,
    fotos: ["/placeholder.svg?width=800&height=600", "/placeholder.svg?width=800&height=600"],
    plano: "destaque",
    verificado: true,
    favoritos: [],
    dataCadastro: new Date(Date.now() - 86400000 * 1), // 1 dia atrás
    status: "ativo",
    cidade: "Belo Horizonte",
    views: 2341,
    likes: 210,
    shares: 68,
  },
  // Adicione mais veículos se necessário, seguindo o padrão
]
